language: node_js
node_js:
  - "10.16.3"

install:
  - npm i

before_script:
  - npm run build-prod

deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  target_branch: gh-pages
  on:
    branch: master
